// <auto-generated>
/*
 * OpenVIP API
 *
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}'  # Text-to-speech curl -X POST http://localhost:8770/speech \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"speech\", \"text\": \"hello world\", \"language\": \"en\"}' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using OpenVip.Client;
using OpenVip.Model;
using System.Diagnostics.CodeAnalysis;

namespace OpenVip.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IMessagesApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        MessagesApiEvents Events { get; }

        /// <summary>
        /// Send message to agent
        /// </summary>
        /// <remarks>
        /// Send a voice interaction message to a specific agent. The agent must be connected via SSE (GET endpoint) to receive messages. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="agentId">Agent identifier</param>
        /// <param name="transcription"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISendMessageApiResponse"/>&gt;</returns>
        Task<ISendMessageApiResponse> SendMessageAsync(string agentId, Transcription transcription, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Send message to agent
        /// </summary>
        /// <remarks>
        /// Send a voice interaction message to a specific agent. The agent must be connected via SSE (GET endpoint) to receive messages. 
        /// </remarks>
        /// <param name="agentId">Agent identifier</param>
        /// <param name="transcription"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISendMessageApiResponse"/>?&gt;</returns>
        Task<ISendMessageApiResponse?> SendMessageOrDefaultAsync(string agentId, Transcription transcription, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Subscribe to agent messages (SSE)
        /// </summary>
        /// <remarks>
        /// Server-Sent Events stream for messages to this agent.  The SSE connection acts as agent registration — the agent exists as long as this connection is open. When the client disconnects, the agent is automatically de-registered.  Reconnect on disconnect. Messages sent while disconnected are lost (ephemeral model).  Keepalive comments (&#x60;: keepalive&#x60;) are sent every 30 seconds if no data. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="agentId">Agent identifier</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISubscribeAgentApiResponse"/>&gt;</returns>
        Task<ISubscribeAgentApiResponse> SubscribeAgentAsync(string agentId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Subscribe to agent messages (SSE)
        /// </summary>
        /// <remarks>
        /// Server-Sent Events stream for messages to this agent.  The SSE connection acts as agent registration — the agent exists as long as this connection is open. When the client disconnects, the agent is automatically de-registered.  Reconnect on disconnect. Messages sent while disconnected are lost (ephemeral model).  Keepalive comments (&#x60;: keepalive&#x60;) are sent every 30 seconds if no data. 
        /// </remarks>
        /// <param name="agentId">Agent identifier</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISubscribeAgentApiResponse"/>?&gt;</returns>
        Task<ISubscribeAgentApiResponse?> SubscribeAgentOrDefaultAsync(string agentId, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="ISendMessageApiResponse"/>
    /// </summary>
    public interface ISendMessageApiResponse : OpenVip.Client.IApiResponse, IOk<OpenVip.Model.Ack?>, IBadRequest<OpenVip.Model.Error?>, INotFound<OpenVip.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }
    }

    /// <summary>
    /// The <see cref="ISubscribeAgentApiResponse"/>
    /// </summary>
    public interface ISubscribeAgentApiResponse : OpenVip.Client.IApiResponse, IOk<string?>, IConflict<OpenVip.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 409 Conflict
        /// </summary>
        /// <returns></returns>
        bool IsConflict { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class MessagesApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnSendMessage;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorSendMessage;

        internal void ExecuteOnSendMessage(MessagesApi.SendMessageApiResponse apiResponse)
        {
            OnSendMessage?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorSendMessage(Exception exception)
        {
            OnErrorSendMessage?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnSubscribeAgent;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorSubscribeAgent;

        internal void ExecuteOnSubscribeAgent(MessagesApi.SubscribeAgentApiResponse apiResponse)
        {
            OnSubscribeAgent?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorSubscribeAgent(Exception exception)
        {
            OnErrorSubscribeAgent?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class MessagesApi : IMessagesApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<MessagesApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public MessagesApiEvents Events { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="MessagesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MessagesApi(ILogger<MessagesApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, MessagesApiEvents messagesApiEvents)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<MessagesApi>();
            HttpClient = httpClient;
            Events = messagesApiEvents;
        }

        partial void FormatSendMessage(ref string agentId, Transcription transcription);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="agentId"></param>
        /// <param name="transcription"></param>
        /// <returns></returns>
        private void ValidateSendMessage(string agentId, Transcription transcription)
        {
            if (agentId == null)
                throw new ArgumentNullException(nameof(agentId));

            if (transcription == null)
                throw new ArgumentNullException(nameof(transcription));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="agentId"></param>
        /// <param name="transcription"></param>
        private void AfterSendMessageDefaultImplementation(ISendMessageApiResponse apiResponseLocalVar, string agentId, Transcription transcription)
        {
            bool suppressDefaultLog = false;
            AfterSendMessage(ref suppressDefaultLog, apiResponseLocalVar, agentId, transcription);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="agentId"></param>
        /// <param name="transcription"></param>
        partial void AfterSendMessage(ref bool suppressDefaultLog, ISendMessageApiResponse apiResponseLocalVar, string agentId, Transcription transcription);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="agentId"></param>
        /// <param name="transcription"></param>
        private void OnErrorSendMessageDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string agentId, Transcription transcription)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorSendMessage(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, agentId, transcription);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="agentId"></param>
        /// <param name="transcription"></param>
        partial void OnErrorSendMessage(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string agentId, Transcription transcription);

        /// <summary>
        /// Send message to agent Send a voice interaction message to a specific agent. The agent must be connected via SSE (GET endpoint) to receive messages. 
        /// </summary>
        /// <param name="agentId">Agent identifier</param>
        /// <param name="transcription"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISendMessageApiResponse"/>&gt;</returns>
        public async Task<ISendMessageApiResponse?> SendMessageOrDefaultAsync(string agentId, Transcription transcription, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await SendMessageAsync(agentId, transcription, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Send message to agent Send a voice interaction message to a specific agent. The agent must be connected via SSE (GET endpoint) to receive messages. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="agentId">Agent identifier</param>
        /// <param name="transcription"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISendMessageApiResponse"/>&gt;</returns>
        public async Task<ISendMessageApiResponse> SendMessageAsync(string agentId, Transcription transcription, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateSendMessage(agentId, transcription);

                FormatSendMessage(ref agentId, transcription);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/agents/{agent_id}/messages"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/agents/{agent_id}/messages");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bagent_id%7D", Uri.EscapeDataString(agentId.ToString()));

                    httpRequestMessageLocalVar.Content = (transcription as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(transcription, _jsonSerializerOptions));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<SendMessageApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<SendMessageApiResponse>();
                        SendMessageApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/agents/{agent_id}/messages", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterSendMessageDefaultImplementation(apiResponseLocalVar, agentId, transcription);

                        Events.ExecuteOnSendMessage(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorSendMessageDefaultImplementation(e, "/agents/{agent_id}/messages", uriBuilderLocalVar.Path, agentId, transcription);
                Events.ExecuteOnErrorSendMessage(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="SendMessageApiResponse"/>
        /// </summary>
        public partial class SendMessageApiResponse : OpenVip.Client.ApiResponse, ISendMessageApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<SendMessageApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="SendMessageApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public SendMessageApiResponse(ILogger<SendMessageApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="SendMessageApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public SendMessageApiResponse(ILogger<SendMessageApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public OpenVip.Model.Ack? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<OpenVip.Model.Ack>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out OpenVip.Model.Ack? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public OpenVip.Model.Error? BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<OpenVip.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out OpenVip.Model.Error? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public OpenVip.Model.Error? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<OpenVip.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out OpenVip.Model.Error? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatSubscribeAgent(ref string agentId);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="agentId"></param>
        /// <returns></returns>
        private void ValidateSubscribeAgent(string agentId)
        {
            if (agentId == null)
                throw new ArgumentNullException(nameof(agentId));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="agentId"></param>
        private void AfterSubscribeAgentDefaultImplementation(ISubscribeAgentApiResponse apiResponseLocalVar, string agentId)
        {
            bool suppressDefaultLog = false;
            AfterSubscribeAgent(ref suppressDefaultLog, apiResponseLocalVar, agentId);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="agentId"></param>
        partial void AfterSubscribeAgent(ref bool suppressDefaultLog, ISubscribeAgentApiResponse apiResponseLocalVar, string agentId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="agentId"></param>
        private void OnErrorSubscribeAgentDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string agentId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorSubscribeAgent(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, agentId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="agentId"></param>
        partial void OnErrorSubscribeAgent(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string agentId);

        /// <summary>
        /// Subscribe to agent messages (SSE) Server-Sent Events stream for messages to this agent.  The SSE connection acts as agent registration — the agent exists as long as this connection is open. When the client disconnects, the agent is automatically de-registered.  Reconnect on disconnect. Messages sent while disconnected are lost (ephemeral model).  Keepalive comments (&#x60;: keepalive&#x60;) are sent every 30 seconds if no data. 
        /// </summary>
        /// <param name="agentId">Agent identifier</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISubscribeAgentApiResponse"/>&gt;</returns>
        public async Task<ISubscribeAgentApiResponse?> SubscribeAgentOrDefaultAsync(string agentId, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await SubscribeAgentAsync(agentId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Subscribe to agent messages (SSE) Server-Sent Events stream for messages to this agent.  The SSE connection acts as agent registration — the agent exists as long as this connection is open. When the client disconnects, the agent is automatically de-registered.  Reconnect on disconnect. Messages sent while disconnected are lost (ephemeral model).  Keepalive comments (&#x60;: keepalive&#x60;) are sent every 30 seconds if no data. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="agentId">Agent identifier</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISubscribeAgentApiResponse"/>&gt;</returns>
        public async Task<ISubscribeAgentApiResponse> SubscribeAgentAsync(string agentId, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateSubscribeAgent(agentId);

                FormatSubscribeAgent(ref agentId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/agents/{agent_id}/messages"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/agents/{agent_id}/messages");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bagent_id%7D", Uri.EscapeDataString(agentId.ToString()));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "text/event-stream",
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<SubscribeAgentApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<SubscribeAgentApiResponse>();
                        SubscribeAgentApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/agents/{agent_id}/messages", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterSubscribeAgentDefaultImplementation(apiResponseLocalVar, agentId);

                        Events.ExecuteOnSubscribeAgent(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorSubscribeAgentDefaultImplementation(e, "/agents/{agent_id}/messages", uriBuilderLocalVar.Path, agentId);
                Events.ExecuteOnErrorSubscribeAgent(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="SubscribeAgentApiResponse"/>
        /// </summary>
        public partial class SubscribeAgentApiResponse : OpenVip.Client.ApiResponse, ISubscribeAgentApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<SubscribeAgentApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="SubscribeAgentApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public SubscribeAgentApiResponse(ILogger<SubscribeAgentApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="SubscribeAgentApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public SubscribeAgentApiResponse(ILogger<SubscribeAgentApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public string? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<string>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out string? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 409 Conflict
            /// </summary>
            /// <returns></returns>
            public bool IsConflict => 409 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 409 Conflict
            /// </summary>
            /// <returns></returns>
            public OpenVip.Model.Error? Conflict()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsConflict
                    ? System.Text.Json.JsonSerializer.Deserialize<OpenVip.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 409 Conflict and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryConflict([NotNullWhen(true)]out OpenVip.Model.Error? result)
            {
                result = null;

                try
                {
                    result = Conflict();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)409);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
