/*
 * OpenVIP API
 *
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}'  # Text-to-speech curl -X POST http://localhost:8770/speech \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"speech\", \"text\": \"hello world\", \"language\": \"en\"}' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System.Collections.Generic;
using System.Security.Cryptography;
using OpenVip.Client;
using OpenVip.Api;
using OpenVip.Extensions;
using Xunit;

namespace OpenVip.Test.Api
{
    /// <summary>
    ///  Tests the dependency injection.
    /// </summary>
    public class DependencyInjectionTest
    {
        private readonly IHost _hostUsingConfigureWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((context, services, options) =>
            {

            })
            .Build();

        private readonly IHost _hostUsingConfigureWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((context, services, options) =>
            {

                options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
            })
            .Build();

        private readonly IHost _hostUsingAddWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {

                });
            })
            .Build();

        private readonly IHost _hostUsingAddWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {

                    options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
                });
            })
            .Build();

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithAClientTest()
        {
            var controlApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IControlApi>();
            Assert.True(controlApi.HttpClient.BaseAddress != null);

            var messagesApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IMessagesApi>();
            Assert.True(messagesApi.HttpClient.BaseAddress != null);

            var speechApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<ISpeechApi>();
            Assert.True(speechApi.HttpClient.BaseAddress != null);

            var statusApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IStatusApi>();
            Assert.True(statusApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithoutAClientTest()
        {
            var controlApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IControlApi>();
            Assert.True(controlApi.HttpClient.BaseAddress != null);

            var messagesApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IMessagesApi>();
            Assert.True(messagesApi.HttpClient.BaseAddress != null);

            var speechApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<ISpeechApi>();
            Assert.True(speechApi.HttpClient.BaseAddress != null);

            var statusApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IStatusApi>();
            Assert.True(statusApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithAClientTest()
        {
            var controlApi = _hostUsingAddWithAClient.Services.GetRequiredService<IControlApi>();
            Assert.True(controlApi.HttpClient.BaseAddress != null);
            
            var messagesApi = _hostUsingAddWithAClient.Services.GetRequiredService<IMessagesApi>();
            Assert.True(messagesApi.HttpClient.BaseAddress != null);
            
            var speechApi = _hostUsingAddWithAClient.Services.GetRequiredService<ISpeechApi>();
            Assert.True(speechApi.HttpClient.BaseAddress != null);
            
            var statusApi = _hostUsingAddWithAClient.Services.GetRequiredService<IStatusApi>();
            Assert.True(statusApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithoutAClientTest()
        {
            var controlApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IControlApi>();
            Assert.True(controlApi.HttpClient.BaseAddress != null);

            var messagesApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IMessagesApi>();
            Assert.True(messagesApi.HttpClient.BaseAddress != null);

            var speechApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<ISpeechApi>();
            Assert.True(speechApi.HttpClient.BaseAddress != null);

            var statusApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IStatusApi>();
            Assert.True(statusApi.HttpClient.BaseAddress != null);
        }
    }
}
