# coding: utf-8

"""
    OpenVIP API

    Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}'  # Text-to-speech curl -X POST http://localhost:8770/speech \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"speech\", \"text\": \"hello world\", \"language\": \"en\"}' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class Transcription(BaseModel):
    """
    Voice transcription message
    """ # noqa: E501
    openvip: StrictStr = Field(description="Protocol version")
    type: StrictStr = Field(description="Message type")
    id: UUID = Field(description="Unique message identifier")
    timestamp: datetime = Field(description="ISO 8601 timestamp")
    text: StrictStr = Field(description="Transcribed text")
    origin: Optional[StrictStr] = Field(default=None, description="Producer identifier")
    language: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="BCP 47 language tag")
    confidence: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, description="Transcription confidence score")
    partial: Optional[StrictBool] = Field(default=None, description="If true, this is an incomplete transcription in progress")
    trace_id: Optional[UUID] = Field(default=None, description="ID of the original message (OpenTelemetry-style)")
    parent_id: Optional[UUID] = Field(default=None, description="ID of the parent message (OpenTelemetry-style)")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["openvip", "type", "id", "timestamp", "text", "origin", "language", "confidence", "partial", "trace_id", "parent_id"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['transcription']):
            raise ValueError("must be one of enum values ('transcription')")
        return value

    @field_validator('language')
    def language_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z]{2}(-[A-Z]{2})?$", value):
            raise ValueError(r"must validate the regular expression /^[a-z]{2}(-[A-Z]{2})?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Transcription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Transcription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "openvip": obj.get("openvip"),
            "type": obj.get("type"),
            "id": obj.get("id"),
            "timestamp": obj.get("timestamp"),
            "text": obj.get("text"),
            "origin": obj.get("origin"),
            "language": obj.get("language"),
            "confidence": obj.get("confidence"),
            "partial": obj.get("partial"),
            "trace_id": obj.get("trace_id"),
            "parent_id": obj.get("parent_id")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


