/* tslint:disable */
/* eslint-disable */
/**
 * OpenVIP API
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}\'  # Text-to-speech curl -X POST http://localhost:8770/speech \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"speech\", \"text\": \"hello world\", \"language\": \"en\"}\' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Control command request
 * @export
 * @interface ControlRequest
 */
export interface ControlRequest {
    /**
     * Command to execute
     * @type {ControlRequestCommandEnum}
     * @memberof ControlRequest
     */
    command: ControlRequestCommandEnum;
}


/**
 * @export
 */
export const ControlRequestCommandEnum = {
    SttStart: 'stt.start',
    SttStop: 'stt.stop',
    EngineShutdown: 'engine.shutdown'
} as const;
export type ControlRequestCommandEnum = typeof ControlRequestCommandEnum[keyof typeof ControlRequestCommandEnum];


/**
 * Check if a given object implements the ControlRequest interface.
 */
export function instanceOfControlRequest(value: object): value is ControlRequest {
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function ControlRequestFromJSON(json: any): ControlRequest {
    return ControlRequestFromJSONTyped(json, false);
}

export function ControlRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControlRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'command': json['command'],
    };
}

export function ControlRequestToJSON(json: any): ControlRequest {
    return ControlRequestToJSONTyped(json, false);
}

export function ControlRequestToJSONTyped(value?: ControlRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command': value['command'],
    };
}

