/* tslint:disable */
/* eslint-disable */
/**
 * OpenVIP API
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}\'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}\' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard extension: text input behavior. ops is an ordered list of input operations to perform.
 * @export
 * @interface MessageXInput
 */
export interface MessageXInput {
    /**
     * Ordered list of input operations to perform
     * @type {Array<MessageXInputOpsEnum>}
     * @memberof MessageXInput
     */
    ops: Array<MessageXInputOpsEnum>;
    /**
     * The voice phrase that triggered this action
     * @type {string}
     * @memberof MessageXInput
     */
    trigger?: string;
    /**
     * Confidence score for the trigger (0.0–1.0)
     * @type {number}
     * @memberof MessageXInput
     */
    confidence?: number;
    /**
     * Generator identifier — free-form string identifying the component that produced this extension
     * @type {string}
     * @memberof MessageXInput
     */
    source?: string;
}


/**
 * @export
 */
export const MessageXInputOpsEnum = {
    Submit: 'submit',
    Newline: 'newline'
} as const;
export type MessageXInputOpsEnum = typeof MessageXInputOpsEnum[keyof typeof MessageXInputOpsEnum];


/**
 * Check if a given object implements the MessageXInput interface.
 */
export function instanceOfMessageXInput(value: object): value is MessageXInput {
    if (!('ops' in value) || value['ops'] === undefined) return false;
    return true;
}

export function MessageXInputFromJSON(json: any): MessageXInput {
    return MessageXInputFromJSONTyped(json, false);
}

export function MessageXInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageXInput {
    if (json == null) {
        return json;
    }
    return {
        
        'ops': json['ops'],
        'trigger': json['trigger'] == null ? undefined : json['trigger'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function MessageXInputToJSON(json: any): MessageXInput {
    return MessageXInputToJSONTyped(json, false);
}

export function MessageXInputToJSONTyped(value?: MessageXInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ops': value['ops'],
        'trigger': value['trigger'],
        'confidence': value['confidence'],
        'source': value['source'],
    };
}

