/* tslint:disable */
/* eslint-disable */
/**
 * OpenVIP API
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}\'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}\' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error response
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * Protocol version
     * @type {ModelErrorOpenvipEnum}
     * @memberof ModelError
     */
    openvip: ModelErrorOpenvipEnum;
    /**
     * Human-readable error message
     * @type {string}
     * @memberof ModelError
     */
    error: string;
    /**
     * Machine-readable error code
     * @type {ModelErrorCodeEnum}
     * @memberof ModelError
     */
    code?: ModelErrorCodeEnum;
    /**
     * Unique identifier for this error (assigned by the engine)
     * @type {string}
     * @memberof ModelError
     */
    id?: string;
    /**
     * ID of the request that caused this error
     * @type {string}
     * @memberof ModelError
     */
    ref?: string;
}


/**
 * @export
 */
export const ModelErrorOpenvipEnum = {
    _10: '1.0'
} as const;
export type ModelErrorOpenvipEnum = typeof ModelErrorOpenvipEnum[keyof typeof ModelErrorOpenvipEnum];

/**
 * @export
 */
export const ModelErrorCodeEnum = {
    InvalidFormat: 'INVALID_FORMAT',
    MissingField: 'MISSING_FIELD',
    NotFound: 'NOT_FOUND',
    Conflict: 'CONFLICT',
    InternalError: 'INTERNAL_ERROR'
} as const;
export type ModelErrorCodeEnum = typeof ModelErrorCodeEnum[keyof typeof ModelErrorCodeEnum];


/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): value is ModelError {
    if (!('openvip' in value) || value['openvip'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if (json == null) {
        return json;
    }
    return {
        
        'openvip': json['openvip'],
        'error': json['error'],
        'code': json['code'] == null ? undefined : json['code'],
        'id': json['id'] == null ? undefined : json['id'],
        'ref': json['ref'] == null ? undefined : json['ref'],
    };
}

export function ModelErrorToJSON(json: any): ModelError {
    return ModelErrorToJSONTyped(json, false);
}

export function ModelErrorToJSONTyped(value?: ModelError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'openvip': value['openvip'],
        'error': value['error'],
        'code': value['code'],
        'id': value['id'],
        'ref': value['ref'],
    };
}

