/* tslint:disable */
/* eslint-disable */
/**
 * OpenVIP API
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}\'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}\' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Operation response
 * @export
 * @interface Response
 */
export interface Response {
    /**
     * Protocol version
     * @type {ResponseOpenvipEnum}
     * @memberof Response
     */
    openvip: ResponseOpenvipEnum;
    /**
     * Operation status
     * @type {ResponseStatusEnum}
     * @memberof Response
     */
    status: ResponseStatusEnum;
    /**
     * Unique identifier for this response (assigned by the engine)
     * @type {string}
     * @memberof Response
     */
    id?: string;
    /**
     * ID of the request that triggered this response
     * @type {string}
     * @memberof Response
     */
    ref?: string;
}


/**
 * @export
 */
export const ResponseOpenvipEnum = {
    _10: '1.0'
} as const;
export type ResponseOpenvipEnum = typeof ResponseOpenvipEnum[keyof typeof ResponseOpenvipEnum];

/**
 * @export
 */
export const ResponseStatusEnum = {
    Ok: 'ok'
} as const;
export type ResponseStatusEnum = typeof ResponseStatusEnum[keyof typeof ResponseStatusEnum];


/**
 * Check if a given object implements the Response interface.
 */
export function instanceOfResponse(value: object): value is Response {
    if (!('openvip' in value) || value['openvip'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ResponseFromJSON(json: any): Response {
    return ResponseFromJSONTyped(json, false);
}

export function ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Response {
    if (json == null) {
        return json;
    }
    return {
        
        'openvip': json['openvip'],
        'status': json['status'],
        'id': json['id'] == null ? undefined : json['id'],
        'ref': json['ref'] == null ? undefined : json['ref'],
    };
}

export function ResponseToJSON(json: any): Response {
    return ResponseToJSONTyped(json, false);
}

export function ResponseToJSONTyped(value?: Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'openvip': value['openvip'],
        'status': value['status'],
        'id': value['id'],
        'ref': value['ref'],
    };
}

