/* tslint:disable */
/* eslint-disable */
/**
 * OpenVIP API
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}\'  # Text-to-speech curl -X POST http://localhost:8770/speech \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"speech\", \"text\": \"hello world\", \"language\": \"en\"}\' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Text-to-speech request
 * @export
 * @interface SpeechRequest
 */
export interface SpeechRequest {
    /**
     * Protocol version
     * @type {string}
     * @memberof SpeechRequest
     */
    openvip: string;
    /**
     * Message type
     * @type {SpeechRequestTypeEnum}
     * @memberof SpeechRequest
     */
    type: SpeechRequestTypeEnum;
    /**
     * Text to synthesize
     * @type {string}
     * @memberof SpeechRequest
     */
    text: string;
    /**
     * BCP 47 language tag
     * @type {string}
     * @memberof SpeechRequest
     */
    language?: string;
}


/**
 * @export
 */
export const SpeechRequestTypeEnum = {
    Speech: 'speech'
} as const;
export type SpeechRequestTypeEnum = typeof SpeechRequestTypeEnum[keyof typeof SpeechRequestTypeEnum];


/**
 * Check if a given object implements the SpeechRequest interface.
 */
export function instanceOfSpeechRequest(value: object): value is SpeechRequest {
    if (!('openvip' in value) || value['openvip'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function SpeechRequestFromJSON(json: any): SpeechRequest {
    return SpeechRequestFromJSONTyped(json, false);
}

export function SpeechRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpeechRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'openvip': json['openvip'],
        'type': json['type'],
        'text': json['text'],
        'language': json['language'] == null ? undefined : json['language'],
    };
}

export function SpeechRequestToJSON(json: any): SpeechRequest {
    return SpeechRequestToJSONTyped(json, false);
}

export function SpeechRequestToJSONTyped(value?: SpeechRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'openvip': value['openvip'],
        'type': value['type'],
        'text': value['text'],
        'language': value['language'],
    };
}

