/* tslint:disable */
/* eslint-disable */
/**
 * OpenVIP API
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}\'  # Text-to-speech curl -X POST http://localhost:8770/speech \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"speech\", \"text\": \"hello world\", \"language\": \"en\"}\' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Engine status
 * @export
 * @interface Status
 */
export interface Status {
    /**
     * Supported OpenVIP protocol version
     * @type {string}
     * @memberof Status
     */
    protocolVersion?: string;
    /**
     * Current engine state
     * @type {string}
     * @memberof Status
     */
    state?: string;
    /**
     * List of connected agent identifiers
     * @type {Array<string>}
     * @memberof Status
     */
    connectedAgents?: Array<string>;
    /**
     * Implementation-specific details (opaque to protocol)
     * @type {{ [key: string]: any; }}
     * @memberof Status
     */
    platform?: { [key: string]: any; };
}

/**
 * Check if a given object implements the Status interface.
 */
export function instanceOfStatus(value: object): value is Status {
    return true;
}

export function StatusFromJSON(json: any): Status {
    return StatusFromJSONTyped(json, false);
}

export function StatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): Status {
    if (json == null) {
        return json;
    }
    return {
        
        'protocolVersion': json['protocol_version'] == null ? undefined : json['protocol_version'],
        'state': json['state'] == null ? undefined : json['state'],
        'connectedAgents': json['connected_agents'] == null ? undefined : json['connected_agents'],
        'platform': json['platform'] == null ? undefined : json['platform'],
    };
}

export function StatusToJSON(json: any): Status {
    return StatusToJSONTyped(json, false);
}

export function StatusToJSONTyped(value?: Status | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'protocol_version': value['protocolVersion'],
        'state': value['state'],
        'connected_agents': value['connectedAgents'],
        'platform': value['platform'],
    };
}

