/* tslint:disable */
/* eslint-disable */
/**
 * OpenVIP API
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}\'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}\' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Speech-to-text service status
 * @export
 * @interface StatusStt
 */
export interface StatusStt {
    /**
     * STT service available on this engine
     * @type {boolean}
     * @memberof StatusStt
     */
    enabled?: boolean;
    /**
     * Microphone is currently listening
     * @type {boolean}
     * @memberof StatusStt
     */
    active?: boolean;
}

/**
 * Check if a given object implements the StatusStt interface.
 */
export function instanceOfStatusStt(value: object): value is StatusStt {
    return true;
}

export function StatusSttFromJSON(json: any): StatusStt {
    return StatusSttFromJSONTyped(json, false);
}

export function StatusSttFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusStt {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function StatusSttToJSON(json: any): StatusStt {
    return StatusSttToJSONTyped(json, false);
}

export function StatusSttToJSONTyped(value?: StatusStt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'active': value['active'],
    };
}

