/* tslint:disable */
/* eslint-disable */
/**
 * OpenVIP API
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}\'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}\' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusStt } from './StatusStt';
import {
    StatusSttFromJSON,
    StatusSttFromJSONTyped,
    StatusSttToJSON,
    StatusSttToJSONTyped,
} from './StatusStt';
import type { StatusTts } from './StatusTts';
import {
    StatusTtsFromJSON,
    StatusTtsFromJSONTyped,
    StatusTtsToJSON,
    StatusTtsToJSONTyped,
} from './StatusTts';

/**
 * Engine status
 * @export
 * @interface Status
 */
export interface Status {
    /**
     * Protocol version
     * @type {StatusOpenvipEnum}
     * @memberof Status
     */
    openvip: StatusOpenvipEnum;
    /**
     * 
     * @type {StatusStt}
     * @memberof Status
     */
    stt?: StatusStt;
    /**
     * 
     * @type {StatusTts}
     * @memberof Status
     */
    tts?: StatusTts;
    /**
     * List of connected agent identifiers
     * @type {Array<string>}
     * @memberof Status
     */
    connectedAgents?: Array<string>;
    /**
     * Implementation-specific details (opaque to protocol)
     * @type {{ [key: string]: any; }}
     * @memberof Status
     */
    platform?: { [key: string]: any; };
}


/**
 * @export
 */
export const StatusOpenvipEnum = {
    _10: '1.0'
} as const;
export type StatusOpenvipEnum = typeof StatusOpenvipEnum[keyof typeof StatusOpenvipEnum];


/**
 * Check if a given object implements the Status interface.
 */
export function instanceOfStatus(value: object): value is Status {
    if (!('openvip' in value) || value['openvip'] === undefined) return false;
    return true;
}

export function StatusFromJSON(json: any): Status {
    return StatusFromJSONTyped(json, false);
}

export function StatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): Status {
    if (json == null) {
        return json;
    }
    return {
        
        'openvip': json['openvip'],
        'stt': json['stt'] == null ? undefined : StatusSttFromJSON(json['stt']),
        'tts': json['tts'] == null ? undefined : StatusTtsFromJSON(json['tts']),
        'connectedAgents': json['connected_agents'] == null ? undefined : json['connected_agents'],
        'platform': json['platform'] == null ? undefined : json['platform'],
    };
}

export function StatusToJSON(json: any): Status {
    return StatusToJSONTyped(json, false);
}

export function StatusToJSONTyped(value?: Status | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'openvip': value['openvip'],
        'stt': StatusSttToJSON(value['stt']),
        'tts': StatusTtsToJSON(value['tts']),
        'connected_agents': value['connectedAgents'],
        'platform': value['platform'],
    };
}

