/* tslint:disable */
/* eslint-disable */
/**
 * OpenVIP API
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}\'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}\' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageXInput } from './MessageXInput';
import {
    MessageXInputFromJSON,
    MessageXInputFromJSONTyped,
    MessageXInputToJSON,
    MessageXInputToJSONTyped,
} from './MessageXInput';
import type { MessageXAgentSwitch } from './MessageXAgentSwitch';
import {
    MessageXAgentSwitchFromJSON,
    MessageXAgentSwitchFromJSONTyped,
    MessageXAgentSwitchToJSON,
    MessageXAgentSwitchToJSONTyped,
} from './MessageXAgentSwitch';

/**
 * Voice transcription message
 * @export
 * @interface Transcription
 */
export interface Transcription {
    /**
     * Protocol version
     * @type {TranscriptionOpenvipEnum}
     * @memberof Transcription
     */
    openvip: TranscriptionOpenvipEnum;
    /**
     * 
     * @type {TranscriptionTypeEnum}
     * @memberof Transcription
     */
    type: TranscriptionTypeEnum;
    /**
     * Unique message identifier
     * @type {string}
     * @memberof Transcription
     */
    id: string;
    /**
     * ISO 8601 timestamp
     * @type {Date}
     * @memberof Transcription
     */
    timestamp: Date;
    /**
     * Message text content
     * @type {string}
     * @memberof Transcription
     */
    text: string;
    /**
     * Producer identifier
     * @type {string}
     * @memberof Transcription
     */
    origin?: string;
    /**
     * BCP 47 language tag
     * @type {string}
     * @memberof Transcription
     */
    language?: string;
    /**
     * ID of the original message (OpenTelemetry-style)
     * @type {string}
     * @memberof Transcription
     */
    traceId?: string;
    /**
     * ID of the parent message (OpenTelemetry-style)
     * @type {string}
     * @memberof Transcription
     */
    parentId?: string;
    /**
     * 
     * @type {MessageXInput}
     * @memberof Transcription
     */
    xInput?: MessageXInput;
    /**
     * 
     * @type {MessageXAgentSwitch}
     * @memberof Transcription
     */
    xAgentSwitch?: MessageXAgentSwitch;
    /**
     * Transcription confidence score
     * @type {number}
     * @memberof Transcription
     */
    confidence?: number;
    /**
     * If true, this is an incomplete transcription in progress
     * @type {boolean}
     * @memberof Transcription
     */
    partial?: boolean;
}


/**
 * @export
 */
export const TranscriptionOpenvipEnum = {
    _10: '1.0'
} as const;
export type TranscriptionOpenvipEnum = typeof TranscriptionOpenvipEnum[keyof typeof TranscriptionOpenvipEnum];

/**
 * @export
 */
export const TranscriptionTypeEnum = {
    Transcription: 'transcription'
} as const;
export type TranscriptionTypeEnum = typeof TranscriptionTypeEnum[keyof typeof TranscriptionTypeEnum];


/**
 * Check if a given object implements the Transcription interface.
 */
export function instanceOfTranscription(value: object): value is Transcription {
    if (!('openvip' in value) || value['openvip'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function TranscriptionFromJSON(json: any): Transcription {
    return TranscriptionFromJSONTyped(json, false);
}

export function TranscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transcription {
    if (json == null) {
        return json;
    }
    return {
        
        'openvip': json['openvip'],
        'type': json['type'],
        'id': json['id'],
        'timestamp': (new Date(json['timestamp'])),
        'text': json['text'],
        'origin': json['origin'] == null ? undefined : json['origin'],
        'language': json['language'] == null ? undefined : json['language'],
        'traceId': json['trace_id'] == null ? undefined : json['trace_id'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
        'xInput': json['x_input'] == null ? undefined : MessageXInputFromJSON(json['x_input']),
        'xAgentSwitch': json['x_agent_switch'] == null ? undefined : MessageXAgentSwitchFromJSON(json['x_agent_switch']),
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'partial': json['partial'] == null ? undefined : json['partial'],
    };
}

export function TranscriptionToJSON(json: any): Transcription {
    return TranscriptionToJSONTyped(json, false);
}

export function TranscriptionToJSONTyped(value?: Transcription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'openvip': value['openvip'],
        'type': value['type'],
        'id': value['id'],
        'timestamp': value['timestamp'].toISOString(),
        'text': value['text'],
        'origin': value['origin'],
        'language': value['language'],
        'trace_id': value['traceId'],
        'parent_id': value['parentId'],
        'x_input': MessageXInputToJSON(value['xInput']),
        'x_agent_switch': MessageXAgentSwitchToJSON(value['xAgentSwitch']),
        'confidence': value['confidence'],
        'partial': value['partial'],
    };
}

