/*
OpenVIP API

Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openvip

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MessageXAgentSwitch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageXAgentSwitch{}

// MessageXAgentSwitch Standard extension: agent routing
type MessageXAgentSwitch struct {
	// Identifier of the agent to switch to
	Target string `json:"target"`
	// Confidence score (0.0–1.0)
	Confidence *float32 `json:"confidence,omitempty"`
	// Generator identifier — free-form string identifying the component that produced this extension
	Source *string `json:"source,omitempty"`
}

type _MessageXAgentSwitch MessageXAgentSwitch

// NewMessageXAgentSwitch instantiates a new MessageXAgentSwitch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageXAgentSwitch(target string) *MessageXAgentSwitch {
	this := MessageXAgentSwitch{}
	this.Target = target
	return &this
}

// NewMessageXAgentSwitchWithDefaults instantiates a new MessageXAgentSwitch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageXAgentSwitchWithDefaults() *MessageXAgentSwitch {
	this := MessageXAgentSwitch{}
	return &this
}

// GetTarget returns the Target field value
func (o *MessageXAgentSwitch) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *MessageXAgentSwitch) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *MessageXAgentSwitch) SetTarget(v string) {
	o.Target = v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *MessageXAgentSwitch) GetConfidence() float32 {
	if o == nil || IsNil(o.Confidence) {
		var ret float32
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageXAgentSwitch) GetConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *MessageXAgentSwitch) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given float32 and assigns it to the Confidence field.
func (o *MessageXAgentSwitch) SetConfidence(v float32) {
	o.Confidence = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *MessageXAgentSwitch) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageXAgentSwitch) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *MessageXAgentSwitch) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *MessageXAgentSwitch) SetSource(v string) {
	o.Source = &v
}

func (o MessageXAgentSwitch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageXAgentSwitch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["target"] = o.Target
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	return toSerialize, nil
}

func (o *MessageXAgentSwitch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"target",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessageXAgentSwitch := _MessageXAgentSwitch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMessageXAgentSwitch)

	if err != nil {
		return err
	}

	*o = MessageXAgentSwitch(varMessageXAgentSwitch)

	return err
}

type NullableMessageXAgentSwitch struct {
	value *MessageXAgentSwitch
	isSet bool
}

func (v NullableMessageXAgentSwitch) Get() *MessageXAgentSwitch {
	return v.value
}

func (v *NullableMessageXAgentSwitch) Set(val *MessageXAgentSwitch) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageXAgentSwitch) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageXAgentSwitch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageXAgentSwitch(val *MessageXAgentSwitch) *NullableMessageXAgentSwitch {
	return &NullableMessageXAgentSwitch{value: val, isSet: true}
}

func (v NullableMessageXAgentSwitch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageXAgentSwitch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


