/*
OpenVIP API

Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}'  # Text-to-speech curl -X POST http://localhost:8770/speech \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"speech\", \"text\": \"hello world\", \"language\": \"en\"}' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openvip

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the Transcription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Transcription{}

// Transcription Voice transcription message
type Transcription struct {
	// Protocol version
	Openvip string `json:"openvip"`
	// Message type
	Type string `json:"type"`
	// Unique message identifier
	Id string `json:"id"`
	// ISO 8601 timestamp
	Timestamp time.Time `json:"timestamp"`
	// Transcribed text
	Text string `json:"text"`
	// Producer identifier
	Origin *string `json:"origin,omitempty"`
	// BCP 47 language tag
	Language *string `json:"language,omitempty" validate:"regexp=^[a-z]{2}(-[A-Z]{2})?$"`
	// Transcription confidence score
	Confidence *float32 `json:"confidence,omitempty"`
	// If true, this is an incomplete transcription in progress
	Partial *bool `json:"partial,omitempty"`
	// ID of the original message (OpenTelemetry-style)
	TraceId *string `json:"trace_id,omitempty"`
	// ID of the parent message (OpenTelemetry-style)
	ParentId *string `json:"parent_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Transcription Transcription

// NewTranscription instantiates a new Transcription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranscription(openvip string, type_ string, id string, timestamp time.Time, text string) *Transcription {
	this := Transcription{}
	this.Openvip = openvip
	this.Type = type_
	this.Id = id
	this.Timestamp = timestamp
	this.Text = text
	return &this
}

// NewTranscriptionWithDefaults instantiates a new Transcription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranscriptionWithDefaults() *Transcription {
	this := Transcription{}
	return &this
}

// GetOpenvip returns the Openvip field value
func (o *Transcription) GetOpenvip() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Openvip
}

// GetOpenvipOk returns a tuple with the Openvip field value
// and a boolean to check if the value has been set.
func (o *Transcription) GetOpenvipOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Openvip, true
}

// SetOpenvip sets field value
func (o *Transcription) SetOpenvip(v string) {
	o.Openvip = v
}

// GetType returns the Type field value
func (o *Transcription) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Transcription) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Transcription) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *Transcription) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Transcription) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Transcription) SetId(v string) {
	o.Id = v
}

// GetTimestamp returns the Timestamp field value
func (o *Transcription) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *Transcription) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *Transcription) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetText returns the Text field value
func (o *Transcription) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *Transcription) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *Transcription) SetText(v string) {
	o.Text = v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *Transcription) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transcription) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *Transcription) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *Transcription) SetOrigin(v string) {
	o.Origin = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *Transcription) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transcription) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *Transcription) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *Transcription) SetLanguage(v string) {
	o.Language = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *Transcription) GetConfidence() float32 {
	if o == nil || IsNil(o.Confidence) {
		var ret float32
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transcription) GetConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *Transcription) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given float32 and assigns it to the Confidence field.
func (o *Transcription) SetConfidence(v float32) {
	o.Confidence = &v
}

// GetPartial returns the Partial field value if set, zero value otherwise.
func (o *Transcription) GetPartial() bool {
	if o == nil || IsNil(o.Partial) {
		var ret bool
		return ret
	}
	return *o.Partial
}

// GetPartialOk returns a tuple with the Partial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transcription) GetPartialOk() (*bool, bool) {
	if o == nil || IsNil(o.Partial) {
		return nil, false
	}
	return o.Partial, true
}

// HasPartial returns a boolean if a field has been set.
func (o *Transcription) HasPartial() bool {
	if o != nil && !IsNil(o.Partial) {
		return true
	}

	return false
}

// SetPartial gets a reference to the given bool and assigns it to the Partial field.
func (o *Transcription) SetPartial(v bool) {
	o.Partial = &v
}

// GetTraceId returns the TraceId field value if set, zero value otherwise.
func (o *Transcription) GetTraceId() string {
	if o == nil || IsNil(o.TraceId) {
		var ret string
		return ret
	}
	return *o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transcription) GetTraceIdOk() (*string, bool) {
	if o == nil || IsNil(o.TraceId) {
		return nil, false
	}
	return o.TraceId, true
}

// HasTraceId returns a boolean if a field has been set.
func (o *Transcription) HasTraceId() bool {
	if o != nil && !IsNil(o.TraceId) {
		return true
	}

	return false
}

// SetTraceId gets a reference to the given string and assigns it to the TraceId field.
func (o *Transcription) SetTraceId(v string) {
	o.TraceId = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *Transcription) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transcription) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *Transcription) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *Transcription) SetParentId(v string) {
	o.ParentId = &v
}

func (o Transcription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Transcription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["openvip"] = o.Openvip
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["text"] = o.Text
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.Partial) {
		toSerialize["partial"] = o.Partial
	}
	if !IsNil(o.TraceId) {
		toSerialize["trace_id"] = o.TraceId
	}
	if !IsNil(o.ParentId) {
		toSerialize["parent_id"] = o.ParentId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Transcription) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"openvip",
		"type",
		"id",
		"timestamp",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTranscription := _Transcription{}

	err = json.Unmarshal(data, &varTranscription)

	if err != nil {
		return err
	}

	*o = Transcription(varTranscription)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "openvip")
		delete(additionalProperties, "type")
		delete(additionalProperties, "id")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "text")
		delete(additionalProperties, "origin")
		delete(additionalProperties, "language")
		delete(additionalProperties, "confidence")
		delete(additionalProperties, "partial")
		delete(additionalProperties, "trace_id")
		delete(additionalProperties, "parent_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTranscription struct {
	value *Transcription
	isSet bool
}

func (v NullableTranscription) Get() *Transcription {
	return v.value
}

func (v *NullableTranscription) Set(val *Transcription) {
	v.value = val
	v.isSet = true
}

func (v NullableTranscription) IsSet() bool {
	return v.isSet
}

func (v *NullableTranscription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranscription(val *Transcription) *NullableTranscription {
	return &NullableTranscription{value: val, isSet: true}
}

func (v NullableTranscription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranscription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


