/*
OpenVIP API

Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openvip

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SpeechResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpeechResponse{}

// SpeechResponse Speech synthesis response
type SpeechResponse struct {
	// Protocol version
	Openvip string `json:"openvip"`
	Status string `json:"status"`
	// Duration of the synthesized audio in milliseconds
	DurationMs *int32 `json:"duration_ms,omitempty"`
	// Unique identifier for this response (assigned by the engine)
	Id *string `json:"id,omitempty"`
	// ID of the speech request that triggered this response
	Ref *string `json:"ref,omitempty"`
}

type _SpeechResponse SpeechResponse

// NewSpeechResponse instantiates a new SpeechResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpeechResponse(openvip string, status string) *SpeechResponse {
	this := SpeechResponse{}
	this.Openvip = openvip
	this.Status = status
	return &this
}

// NewSpeechResponseWithDefaults instantiates a new SpeechResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpeechResponseWithDefaults() *SpeechResponse {
	this := SpeechResponse{}
	return &this
}

// GetOpenvip returns the Openvip field value
func (o *SpeechResponse) GetOpenvip() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Openvip
}

// GetOpenvipOk returns a tuple with the Openvip field value
// and a boolean to check if the value has been set.
func (o *SpeechResponse) GetOpenvipOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Openvip, true
}

// SetOpenvip sets field value
func (o *SpeechResponse) SetOpenvip(v string) {
	o.Openvip = v
}

// GetStatus returns the Status field value
func (o *SpeechResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SpeechResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SpeechResponse) SetStatus(v string) {
	o.Status = v
}

// GetDurationMs returns the DurationMs field value if set, zero value otherwise.
func (o *SpeechResponse) GetDurationMs() int32 {
	if o == nil || IsNil(o.DurationMs) {
		var ret int32
		return ret
	}
	return *o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpeechResponse) GetDurationMsOk() (*int32, bool) {
	if o == nil || IsNil(o.DurationMs) {
		return nil, false
	}
	return o.DurationMs, true
}

// HasDurationMs returns a boolean if a field has been set.
func (o *SpeechResponse) HasDurationMs() bool {
	if o != nil && !IsNil(o.DurationMs) {
		return true
	}

	return false
}

// SetDurationMs gets a reference to the given int32 and assigns it to the DurationMs field.
func (o *SpeechResponse) SetDurationMs(v int32) {
	o.DurationMs = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SpeechResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpeechResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SpeechResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SpeechResponse) SetId(v string) {
	o.Id = &v
}

// GetRef returns the Ref field value if set, zero value otherwise.
func (o *SpeechResponse) GetRef() string {
	if o == nil || IsNil(o.Ref) {
		var ret string
		return ret
	}
	return *o.Ref
}

// GetRefOk returns a tuple with the Ref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpeechResponse) GetRefOk() (*string, bool) {
	if o == nil || IsNil(o.Ref) {
		return nil, false
	}
	return o.Ref, true
}

// HasRef returns a boolean if a field has been set.
func (o *SpeechResponse) HasRef() bool {
	if o != nil && !IsNil(o.Ref) {
		return true
	}

	return false
}

// SetRef gets a reference to the given string and assigns it to the Ref field.
func (o *SpeechResponse) SetRef(v string) {
	o.Ref = &v
}

func (o SpeechResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpeechResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["openvip"] = o.Openvip
	toSerialize["status"] = o.Status
	if !IsNil(o.DurationMs) {
		toSerialize["duration_ms"] = o.DurationMs
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Ref) {
		toSerialize["ref"] = o.Ref
	}
	return toSerialize, nil
}

func (o *SpeechResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"openvip",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpeechResponse := _SpeechResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpeechResponse)

	if err != nil {
		return err
	}

	*o = SpeechResponse(varSpeechResponse)

	return err
}

type NullableSpeechResponse struct {
	value *SpeechResponse
	isSet bool
}

func (v NullableSpeechResponse) Get() *SpeechResponse {
	return v.value
}

func (v *NullableSpeechResponse) Set(val *SpeechResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSpeechResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSpeechResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpeechResponse(val *SpeechResponse) *NullableSpeechResponse {
	return &NullableSpeechResponse{value: val, isSet: true}
}

func (v NullableSpeechResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpeechResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


