/*
OpenVIP API

Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openvip

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Status type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Status{}

// Status Engine status
type Status struct {
	// Protocol version
	Openvip string `json:"openvip"`
	Stt *StatusStt `json:"stt,omitempty"`
	Tts *StatusTts `json:"tts,omitempty"`
	// List of connected agent identifiers
	ConnectedAgents []string `json:"connected_agents,omitempty"`
	// Implementation-specific details (opaque to protocol)
	Platform map[string]interface{} `json:"platform,omitempty"`
}

type _Status Status

// NewStatus instantiates a new Status object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatus(openvip string) *Status {
	this := Status{}
	this.Openvip = openvip
	return &this
}

// NewStatusWithDefaults instantiates a new Status object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusWithDefaults() *Status {
	this := Status{}
	return &this
}

// GetOpenvip returns the Openvip field value
func (o *Status) GetOpenvip() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Openvip
}

// GetOpenvipOk returns a tuple with the Openvip field value
// and a boolean to check if the value has been set.
func (o *Status) GetOpenvipOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Openvip, true
}

// SetOpenvip sets field value
func (o *Status) SetOpenvip(v string) {
	o.Openvip = v
}

// GetStt returns the Stt field value if set, zero value otherwise.
func (o *Status) GetStt() StatusStt {
	if o == nil || IsNil(o.Stt) {
		var ret StatusStt
		return ret
	}
	return *o.Stt
}

// GetSttOk returns a tuple with the Stt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status) GetSttOk() (*StatusStt, bool) {
	if o == nil || IsNil(o.Stt) {
		return nil, false
	}
	return o.Stt, true
}

// HasStt returns a boolean if a field has been set.
func (o *Status) HasStt() bool {
	if o != nil && !IsNil(o.Stt) {
		return true
	}

	return false
}

// SetStt gets a reference to the given StatusStt and assigns it to the Stt field.
func (o *Status) SetStt(v StatusStt) {
	o.Stt = &v
}

// GetTts returns the Tts field value if set, zero value otherwise.
func (o *Status) GetTts() StatusTts {
	if o == nil || IsNil(o.Tts) {
		var ret StatusTts
		return ret
	}
	return *o.Tts
}

// GetTtsOk returns a tuple with the Tts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status) GetTtsOk() (*StatusTts, bool) {
	if o == nil || IsNil(o.Tts) {
		return nil, false
	}
	return o.Tts, true
}

// HasTts returns a boolean if a field has been set.
func (o *Status) HasTts() bool {
	if o != nil && !IsNil(o.Tts) {
		return true
	}

	return false
}

// SetTts gets a reference to the given StatusTts and assigns it to the Tts field.
func (o *Status) SetTts(v StatusTts) {
	o.Tts = &v
}

// GetConnectedAgents returns the ConnectedAgents field value if set, zero value otherwise.
func (o *Status) GetConnectedAgents() []string {
	if o == nil || IsNil(o.ConnectedAgents) {
		var ret []string
		return ret
	}
	return o.ConnectedAgents
}

// GetConnectedAgentsOk returns a tuple with the ConnectedAgents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status) GetConnectedAgentsOk() ([]string, bool) {
	if o == nil || IsNil(o.ConnectedAgents) {
		return nil, false
	}
	return o.ConnectedAgents, true
}

// HasConnectedAgents returns a boolean if a field has been set.
func (o *Status) HasConnectedAgents() bool {
	if o != nil && !IsNil(o.ConnectedAgents) {
		return true
	}

	return false
}

// SetConnectedAgents gets a reference to the given []string and assigns it to the ConnectedAgents field.
func (o *Status) SetConnectedAgents(v []string) {
	o.ConnectedAgents = v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *Status) GetPlatform() map[string]interface{} {
	if o == nil || IsNil(o.Platform) {
		var ret map[string]interface{}
		return ret
	}
	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status) GetPlatformOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Platform) {
		return map[string]interface{}{}, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *Status) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given map[string]interface{} and assigns it to the Platform field.
func (o *Status) SetPlatform(v map[string]interface{}) {
	o.Platform = v
}

func (o Status) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Status) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["openvip"] = o.Openvip
	if !IsNil(o.Stt) {
		toSerialize["stt"] = o.Stt
	}
	if !IsNil(o.Tts) {
		toSerialize["tts"] = o.Tts
	}
	if !IsNil(o.ConnectedAgents) {
		toSerialize["connected_agents"] = o.ConnectedAgents
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	return toSerialize, nil
}

func (o *Status) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"openvip",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatus := _Status{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStatus)

	if err != nil {
		return err
	}

	*o = Status(varStatus)

	return err
}

type NullableStatus struct {
	value *Status
	isSet bool
}

func (v NullableStatus) Get() *Status {
	return v.value
}

func (v *NullableStatus) Set(val *Status) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus(val *Status) *NullableStatus {
	return &NullableStatus{value: val, isSet: true}
}

func (v NullableStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


