// <auto-generated>
/*
 * OpenVIP API
 *
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenVip.Client;

namespace OpenVip.Model
{
    /// <summary>
    /// Standard extension: agent routing
    /// </summary>
    public partial class MessageXAgentSwitch : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MessageXAgentSwitch" /> class.
        /// </summary>
        /// <param name="target">Identifier of the agent to switch to</param>
        /// <param name="confidence">Confidence score (0.0–1.0)</param>
        /// <param name="source">Generator identifier — free-form string identifying the component that produced this extension</param>
        [JsonConstructor]
        public MessageXAgentSwitch(string target, Option<decimal?> confidence = default, Option<string?> source = default)
        {
            Target = target;
            ConfidenceOption = confidence;
            SourceOption = source;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Identifier of the agent to switch to
        /// </summary>
        /// <value>Identifier of the agent to switch to</value>
        [JsonPropertyName("target")]
        public string Target { get; set; }

        /// <summary>
        /// Used to track the state of Confidence
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> ConfidenceOption { get; private set; }

        /// <summary>
        /// Confidence score (0.0–1.0)
        /// </summary>
        /// <value>Confidence score (0.0–1.0)</value>
        [JsonPropertyName("confidence")]
        public decimal? Confidence { get { return this.ConfidenceOption; } set { this.ConfidenceOption = new(value); } }

        /// <summary>
        /// Used to track the state of Source
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceOption { get; private set; }

        /// <summary>
        /// Generator identifier — free-form string identifying the component that produced this extension
        /// </summary>
        /// <value>Generator identifier — free-form string identifying the component that produced this extension</value>
        [JsonPropertyName("source")]
        public string? Source { get { return this.SourceOption; } set { this.SourceOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MessageXAgentSwitch {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  Confidence: ").Append(Confidence).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Confidence (decimal) maximum
            if (this.ConfidenceOption.IsSet && this.ConfidenceOption.Value > (decimal)1)
            {
                yield return new ValidationResult("Invalid value for Confidence, must be a value less than or equal to 1.", new [] { "Confidence" });
            }

            // Confidence (decimal) minimum
            if (this.ConfidenceOption.IsSet && this.ConfidenceOption.Value < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for Confidence, must be a value greater than or equal to 0.", new [] { "Confidence" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MessageXAgentSwitch" />
    /// </summary>
    public class MessageXAgentSwitchJsonConverter : JsonConverter<MessageXAgentSwitch>
    {
        /// <summary>
        /// Deserializes json to <see cref="MessageXAgentSwitch" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MessageXAgentSwitch Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> target = default;
            Option<decimal?> confidence = default;
            Option<string?> source = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "target":
                            target = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "confidence":
                            confidence = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "source":
                            source = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!target.IsSet)
                throw new ArgumentException("Property is required for class MessageXAgentSwitch.", nameof(target));

            if (target.IsSet && target.Value == null)
                throw new ArgumentNullException(nameof(target), "Property is not nullable for class MessageXAgentSwitch.");

            if (confidence.IsSet && confidence.Value == null)
                throw new ArgumentNullException(nameof(confidence), "Property is not nullable for class MessageXAgentSwitch.");

            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source), "Property is not nullable for class MessageXAgentSwitch.");

            return new MessageXAgentSwitch(target.Value!, confidence, source);
        }

        /// <summary>
        /// Serializes a <see cref="MessageXAgentSwitch" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="messageXAgentSwitch"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MessageXAgentSwitch messageXAgentSwitch, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, messageXAgentSwitch, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MessageXAgentSwitch" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="messageXAgentSwitch"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MessageXAgentSwitch messageXAgentSwitch, JsonSerializerOptions jsonSerializerOptions)
        {
            if (messageXAgentSwitch.Target == null)
                throw new ArgumentNullException(nameof(messageXAgentSwitch.Target), "Property is required for class MessageXAgentSwitch.");

            if (messageXAgentSwitch.SourceOption.IsSet && messageXAgentSwitch.Source == null)
                throw new ArgumentNullException(nameof(messageXAgentSwitch.Source), "Property is required for class MessageXAgentSwitch.");

            writer.WriteString("target", messageXAgentSwitch.Target);

            if (messageXAgentSwitch.ConfidenceOption.IsSet)
                writer.WriteNumber("confidence", messageXAgentSwitch.ConfidenceOption.Value!.Value);

            if (messageXAgentSwitch.SourceOption.IsSet)
                writer.WriteString("source", messageXAgentSwitch.Source);
        }
    }
}
