// <auto-generated>
/*
 * OpenVIP API
 *
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenVip.Client;

namespace OpenVip.Model
{
    /// <summary>
    /// Operation response
    /// </summary>
    public partial class Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Response" /> class.
        /// </summary>
        /// <param name="openvip">Protocol version</param>
        /// <param name="status">Operation status</param>
        /// <param name="id">Unique identifier for this response (assigned by the engine)</param>
        /// <param name="ref">ID of the request that triggered this response</param>
        [JsonConstructor]
        public Response(OpenvipEnum openvip, StatusEnum status, Option<Guid?> id = default, Option<Guid?> @ref = default)
        {
            Openvip = openvip;
            Status = status;
            IdOption = id;
            RefOption = @ref;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Protocol version
        /// </summary>
        /// <value>Protocol version</value>
        public enum OpenvipEnum
        {
            /// <summary>
            /// Enum _10 for value: 1.0
            /// </summary>
            _10 = 1
        }

        /// <summary>
        /// Returns a <see cref="OpenvipEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static OpenvipEnum OpenvipEnumFromString(string value)
        {
            if (value.Equals("1.0"))
                return OpenvipEnum._10;

            throw new NotImplementedException($"Could not convert value to type OpenvipEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="OpenvipEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OpenvipEnum? OpenvipEnumFromStringOrDefault(string value)
        {
            if (value.Equals("1.0"))
                return OpenvipEnum._10;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="OpenvipEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string OpenvipEnumToJsonValue(OpenvipEnum value)
        {
            if (value == OpenvipEnum._10)
                return "1.0";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Protocol version
        /// </summary>
        /// <value>Protocol version</value>
        [JsonPropertyName("openvip")]
        public OpenvipEnum Openvip { get; set; }

        /// <summary>
        /// Operation status
        /// </summary>
        /// <value>Operation status</value>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Ok for value: ok
            /// </summary>
            Ok = 1
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("ok"))
                return StatusEnum.Ok;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("ok"))
                return StatusEnum.Ok;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Ok)
                return "ok";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Operation status
        /// </summary>
        /// <value>Operation status</value>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Unique identifier for this response (assigned by the engine)
        /// </summary>
        /// <value>Unique identifier for this response (assigned by the engine)</value>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Ref
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> RefOption { get; private set; }

        /// <summary>
        /// ID of the request that triggered this response
        /// </summary>
        /// <value>ID of the request that triggered this response</value>
        [JsonPropertyName("ref")]
        public Guid? Ref { get { return this.RefOption; } set { this.RefOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Response {\n");
            sb.Append("  Openvip: ").Append(Openvip).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Ref: ").Append(Ref).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Response" />
    /// </summary>
    public class ResponseJsonConverter : JsonConverter<Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Response.OpenvipEnum?> openvip = default;
            Option<Response.StatusEnum?> status = default;
            Option<Guid?> id = default;
            Option<Guid?> varRef = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "openvip":
                            string? openvipRawValue = utf8JsonReader.GetString();
                            if (openvipRawValue != null)
                                openvip = new Option<Response.OpenvipEnum?>(Response.OpenvipEnumFromStringOrDefault(openvipRawValue));
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<Response.StatusEnum?>(Response.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "ref":
                            varRef = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!openvip.IsSet)
                throw new ArgumentException("Property is required for class Response.", nameof(openvip));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class Response.", nameof(status));

            if (openvip.IsSet && openvip.Value == null)
                throw new ArgumentNullException(nameof(openvip), "Property is not nullable for class Response.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class Response.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Response.");

            if (varRef.IsSet && varRef.Value == null)
                throw new ArgumentNullException(nameof(varRef), "Property is not nullable for class Response.");

            return new Response(openvip.Value!.Value!, status.Value!.Value!, id, varRef);
        }

        /// <summary>
        /// Serializes a <see cref="Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Response response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Response response, JsonSerializerOptions jsonSerializerOptions)
        {
            var openvipRawValue = Response.OpenvipEnumToJsonValue(response.Openvip);
            writer.WriteString("openvip", openvipRawValue);
            var statusRawValue = Response.StatusEnumToJsonValue(response.Status);
            writer.WriteString("status", statusRawValue);
            if (response.IdOption.IsSet)
                writer.WriteString("id", response.IdOption.Value!.Value);

            if (response.RefOption.IsSet)
                writer.WriteString("ref", response.RefOption.Value!.Value);
        }
    }
}
