// <auto-generated>
/*
 * OpenVIP API
 *
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}'  # Text-to-speech curl -X POST http://localhost:8770/speech \\   -H \"Content-Type: application/json\" \\   -d '{\"openvip\": \"1.0\", \"type\": \"speech\", \"text\": \"hello world\", \"language\": \"en\"}' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenVip.Client;

namespace OpenVip.Model
{
    /// <summary>
    /// Text-to-speech request
    /// </summary>
    public partial class SpeechRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpeechRequest" /> class.
        /// </summary>
        /// <param name="openvip">Protocol version</param>
        /// <param name="type">Message type</param>
        /// <param name="text">Text to synthesize</param>
        /// <param name="language">BCP 47 language tag</param>
        [JsonConstructor]
        public SpeechRequest(string openvip, TypeEnum type, string text, Option<string?> language = default)
        {
            Openvip = openvip;
            Type = type;
            Text = text;
            LanguageOption = language;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Message type
        /// </summary>
        /// <value>Message type</value>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Speech for value: speech
            /// </summary>
            Speech = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("speech"))
                return TypeEnum.Speech;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("speech"))
                return TypeEnum.Speech;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.Speech)
                return "speech";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Message type
        /// </summary>
        /// <value>Message type</value>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Protocol version
        /// </summary>
        /// <value>Protocol version</value>
        /* <example>1.0</example> */
        [JsonPropertyName("openvip")]
        public string Openvip { get; set; }

        /// <summary>
        /// Text to synthesize
        /// </summary>
        /// <value>Text to synthesize</value>
        /* <example>Light turned on</example> */
        [JsonPropertyName("text")]
        public string Text { get; set; }

        /// <summary>
        /// Used to track the state of Language
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LanguageOption { get; private set; }

        /// <summary>
        /// BCP 47 language tag
        /// </summary>
        /// <value>BCP 47 language tag</value>
        /* <example>en</example> */
        [JsonPropertyName("language")]
        public string? Language { get { return this.LanguageOption; } set { this.LanguageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SpeechRequest {\n");
            sb.Append("  Openvip: ").Append(Openvip).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.LanguageOption.Value != null) {
                // Language (string) pattern
                Regex regexLanguage = new Regex(@"^[a-z]{2}(-[A-Z]{2})?$", RegexOptions.CultureInvariant);

                if (this.LanguageOption.Value != null &&!regexLanguage.Match(this.LanguageOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Language, must match a pattern of " + regexLanguage, new [] { "Language" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SpeechRequest" />
    /// </summary>
    public class SpeechRequestJsonConverter : JsonConverter<SpeechRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="SpeechRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SpeechRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> openvip = default;
            Option<SpeechRequest.TypeEnum?> type = default;
            Option<string?> text = default;
            Option<string?> language = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "openvip":
                            openvip = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<SpeechRequest.TypeEnum?>(SpeechRequest.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "text":
                            text = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "language":
                            language = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!openvip.IsSet)
                throw new ArgumentException("Property is required for class SpeechRequest.", nameof(openvip));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class SpeechRequest.", nameof(type));

            if (!text.IsSet)
                throw new ArgumentException("Property is required for class SpeechRequest.", nameof(text));

            if (openvip.IsSet && openvip.Value == null)
                throw new ArgumentNullException(nameof(openvip), "Property is not nullable for class SpeechRequest.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class SpeechRequest.");

            if (text.IsSet && text.Value == null)
                throw new ArgumentNullException(nameof(text), "Property is not nullable for class SpeechRequest.");

            if (language.IsSet && language.Value == null)
                throw new ArgumentNullException(nameof(language), "Property is not nullable for class SpeechRequest.");

            return new SpeechRequest(openvip.Value!, type.Value!.Value!, text.Value!, language);
        }

        /// <summary>
        /// Serializes a <see cref="SpeechRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="speechRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SpeechRequest speechRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, speechRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SpeechRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="speechRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SpeechRequest speechRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (speechRequest.Openvip == null)
                throw new ArgumentNullException(nameof(speechRequest.Openvip), "Property is required for class SpeechRequest.");

            if (speechRequest.Text == null)
                throw new ArgumentNullException(nameof(speechRequest.Text), "Property is required for class SpeechRequest.");

            if (speechRequest.LanguageOption.IsSet && speechRequest.Language == null)
                throw new ArgumentNullException(nameof(speechRequest.Language), "Property is required for class SpeechRequest.");

            writer.WriteString("openvip", speechRequest.Openvip);

            var typeRawValue = SpeechRequest.TypeEnumToJsonValue(speechRequest.Type);
            writer.WriteString("type", typeRawValue);
            writer.WriteString("text", speechRequest.Text);

            if (speechRequest.LanguageOption.IsSet)
                writer.WriteString("language", speechRequest.Language);
        }
    }
}
