/* tslint:disable */
/* eslint-disable */
/**
 * OpenVIP API
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}\'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}\' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Message,
  Response,
} from '../models/index';
import {
    MessageFromJSON,
    MessageToJSON,
    ResponseFromJSON,
    ResponseToJSON,
} from '../models/index';

export interface SendMessageRequest {
    agentId: string;
    message: Message;
}

export interface SubscribeAgentRequest {
    agentId: string;
}

/**
 * 
 */
export class MessagesApi extends runtime.BaseAPI {

    /**
     * Creates request options for sendMessage without sending the request
     */
    async sendMessageRequestOpts(requestParameters: SendMessageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling sendMessage().'
            );
        }

        if (requestParameters['message'] == null) {
            throw new runtime.RequiredError(
                'message',
                'Required parameter "message" was null or undefined when calling sendMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/agents/{agent_id}/messages`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessageToJSON(requestParameters['message']),
        };
    }

    /**
     * Send a voice interaction message to a specific agent. The agent must be connected via SSE (GET endpoint) to receive messages. 
     * Send message to agent
     */
    async sendMessageRaw(requestParameters: SendMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        const requestOptions = await this.sendMessageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Send a voice interaction message to a specific agent. The agent must be connected via SSE (GET endpoint) to receive messages. 
     * Send message to agent
     */
    async sendMessage(requestParameters: SendMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.sendMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for subscribeAgent without sending the request
     */
    async subscribeAgentRequestOpts(requestParameters: SubscribeAgentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling subscribeAgent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/agents/{agent_id}/messages`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Server-Sent Events stream for messages to this agent.  The SSE connection acts as agent registration — the agent exists as long as this connection is open. When the client disconnects, the agent is automatically de-registered.  Reconnect on disconnect. Messages sent while disconnected are lost (ephemeral model).  Keepalive comments (`: keepalive`) are sent every 30 seconds if no data. 
     * Subscribe to agent messages (SSE)
     */
    async subscribeAgentRaw(requestParameters: SubscribeAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.subscribeAgentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Server-Sent Events stream for messages to this agent.  The SSE connection acts as agent registration — the agent exists as long as this connection is open. When the client disconnects, the agent is automatically de-registered.  Reconnect on disconnect. Messages sent while disconnected are lost (ephemeral model).  Keepalive comments (`: keepalive`) are sent every 30 seconds if no data. 
     * Subscribe to agent messages (SSE)
     */
    async subscribeAgent(requestParameters: SubscribeAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.subscribeAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
