/* tslint:disable */
/* eslint-disable */
/**
 * OpenVIP API
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}\'  # Text-to-speech curl -X POST http://localhost:8770/speech \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"speech\", \"text\": \"hello world\", \"language\": \"en\"}\' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SpeechRequest,
  SpeechResponse,
} from '../models/index';
import {
    SpeechRequestFromJSON,
    SpeechRequestToJSON,
    SpeechResponseFromJSON,
    SpeechResponseToJSON,
} from '../models/index';

export interface TextToSpeechRequest {
    speechRequest: SpeechRequest;
}

/**
 * 
 */
export class SpeechApi extends runtime.BaseAPI {

    /**
     * Creates request options for textToSpeech without sending the request
     */
    async textToSpeechRequestOpts(requestParameters: TextToSpeechRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['speechRequest'] == null) {
            throw new runtime.RequiredError(
                'speechRequest',
                'Required parameter "speechRequest" was null or undefined when calling textToSpeech().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/speech`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SpeechRequestToJSON(requestParameters['speechRequest']),
        };
    }

    /**
     * Request text-to-speech synthesis. The engine will speak the provided text. 
     * Text-to-speech request
     */
    async textToSpeechRaw(requestParameters: TextToSpeechRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SpeechResponse>> {
        const requestOptions = await this.textToSpeechRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SpeechResponseFromJSON(jsonValue));
    }

    /**
     * Request text-to-speech synthesis. The engine will speak the provided text. 
     * Text-to-speech request
     */
    async textToSpeech(requestParameters: TextToSpeechRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SpeechResponse> {
        const response = await this.textToSpeechRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
