/* tslint:disable */
/* eslint-disable */
/**
 * OpenVIP API
 * Open Voice Interaction Protocol (OpenVIP) HTTP API specification.  This API allows applications to send and receive voice interaction messages.  ## Base Path  The OpenVIP protocol defines **relative paths** only. The base path is **implementation-defined** — implementations choose where to mount these endpoints. The recommended base path is `/openvip/`.  Implementations SHOULD serve this OpenAPI spec at `{base_path}/openapi.json` for discovery (e.g. `GET /openvip/openapi.json`).  ## Quick Start  ```bash # Subscribe to messages (SSE) — this IS the registration curl http://localhost:8770/openvip/agents/my-agent-id/messages  # Send a message to an agent curl -X POST http://localhost:8770/openvip/agents/my-agent-id/messages \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"transcription\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:00Z\", \"text\": \"hello\"}\'  # Text-to-speech curl -X POST http://localhost:8770/openvip/speech \\   -H \"Content-Type: application/json\" \\   -d \'{\"openvip\": \"1.0\", \"type\": \"speech\", \"id\": \"uuid\", \"timestamp\": \"2026-02-06T10:30:05Z\", \"text\": \"hello world\", \"language\": \"en\"}\' ```  ## Agent Lifecycle  Agents are **ephemeral**. An agent exists only while its SSE connection is open. No explicit registration is needed — connecting to the SSE endpoint registers the agent. Disconnecting automatically de-registers it. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Status,
} from '../models/index';
import {
    StatusFromJSON,
    StatusToJSON,
} from '../models/index';

/**
 * 
 */
export class StatusApi extends runtime.BaseAPI {

    /**
     * Creates request options for getStatus without sending the request
     */
    async getStatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the current status of the engine. Returns protocol-level information (connected agents, protocol version) and implementation-specific details in the `platform` object. 
     * Get engine status
     */
    async getStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Status>> {
        const requestOptions = await this.getStatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusFromJSON(jsonValue));
    }

    /**
     * Get the current status of the engine. Returns protocol-level information (connected agents, protocol version) and implementation-specific details in the `platform` object. 
     * Get engine status
     */
    async getStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Status> {
        const response = await this.getStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for subscribeStatus without sending the request
     */
    async subscribeStatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/status/stream`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Server-Sent Events stream that pushes status updates on state transitions.  Events are sent when `stt`, `tts`, `connected_agents`, or other discrete fields change. Continuously changing fields (e.g., `uptime_seconds`) do not trigger events.  The payload of each event is a `Status` object — the same schema as the `GET /status` response.  Keepalive comments (`: keepalive`) are sent every 30 seconds if no events occur.  Clients that cannot use SSE should fall back to polling `GET /status`. 
     * Subscribe to status changes (SSE)
     */
    async subscribeStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.subscribeStatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Server-Sent Events stream that pushes status updates on state transitions.  Events are sent when `stt`, `tts`, `connected_agents`, or other discrete fields change. Continuously changing fields (e.g., `uptime_seconds`) do not trigger events.  The payload of each event is a `Status` object — the same schema as the `GET /status` response.  Keepalive comments (`: keepalive`) are sent every 30 seconds if no events occur.  Clients that cannot use SSE should fall back to polling `GET /status`. 
     * Subscribe to status changes (SSE)
     */
    async subscribeStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.subscribeStatusRaw(initOverrides);
        return await response.value();
    }

}
